export const RequestExample = {
  data: [
    {
      id: 2,
      title: "title",
      description: "description",
      amount: 200,
      statusId: 1,
      financialPixkey: null,
      financialBank: "banco",
      financialAgency: "agencia",
      financialAccount: "conta",
      createdAt: "2024-05-21T17:58:28.352Z",
      updatedAt: "2024-05-21T17:58:28.352Z",
      deletedAt: null,
      status: {
        id: 1,
        name: "analysis",
        __entity: "RequestStatusEntity",
      },
      helpType: {
        id: 1,
        name: "financial",
        __entity: "RequestHelpTypeEntity",
      },
      user: {
        id: 1,
        email: "admin@coopartilhar.com.br",
        provider: "email",
        socialId: null,
        firstName: "Super",
        lastName: "Admin",
        document: "99999999999",
        telephone: "99999999999",
        createdAt: "2024-05-21T17:16:07.845Z",
        updatedAt: "2024-05-21T17:16:07.845Z",
        deletedAt: null,
        photo: null,
        organization: null,
        role: {
          id: 1,
          name: "Admin",
          __entity: "UserRole",
        },
        status: {
          id: 1,
          name: "Active",
          __entity: "UserStatus",
        },
        addresses: [],
        __entity: "User",
      },
      godFather: {
        id: 2,
        email: "john.stark@coopartilhar.com",
        provider: "email",
        socialId: null,
        firstName: "John",
        lastName: "Stark",
        document: "99999999998",
        telephone: "99999999999",
        createdAt: "2024-05-21T17:16:07.939Z",
        updatedAt: "2024-05-21T17:16:07.939Z",
        deletedAt: null,
        photo: null,
        organization: null,
        role: {
          id: 2,
          name: "User",
          __entity: "UserRole",
        },
        status: {
          id: 1,
          name: "Active",
          __entity: "UserStatus",
        },
        addresses: [
          {
            id: 3,
            street: "Rua Teste",
            complement: "Próximo ao parque",
            number: "1A",
            city: "Cidade ABC",
            locationLatitude: "-29.922854087046",
            locationLongitude: "51.17524989736568",
          },
          {
            id: 1,
            street: "Rua Teste",
            complement: "Próximo ao parque",
            number: "1A",
            city: "Cidade ABC",
            locationLatitude: "-29.922854087046",
            locationLongitude: "51.17524989736568",
          },
          {
            id: 2,
            street: "Rua Teste",
            complement: "Próximo ao parque",
            number: "1A",
            city: "Cidade ABC",
            locationLatitude: "-29.922854087046",
            locationLongitude: "51.17524989736568",
          },
        ],
        __entity: "User",
      },
      __entity: "RequestEntity",
    },
  ],
  hasNextPage: false,
};
